# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog,
# values which you are expected to set up once and rarely need to edit
# after that. For technical reasons, this file is *NOT* reloaded
# automatically when you use 'jekyll serve'. If you change this file,
# please restart the server process.

# Site settings
title: Helpful Potato
author: eucalypto
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog of my computer experience. It is meant to be a help for future-me and anyone with similar problems.
baseurl: "/helpful-potato" # the subpath of your site, e.g. /blog
url: "http://eucalypto.github.io" # the base hostname & protocol for your site
github_username:  eucalypto

# If using a gemfile, you can add gems to a group called
# ":jekyll_plugins". Gems from this group are apparently loaded by
# Jekyll automatically. But you can use both options simultaneoulsly.
gems:
  - jekyll-asciidoc

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Makefile'

# This switch activates or deactivates disqus comments on the whole
# site. Values: true, false.
# To actually display comments in a post, you need to write a site
# variable in the preamble of your post: 'comments: true'
disqus-activate: true


# Build settings
# markdown: kramdown
