# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

gem 'jekyll'
gem 'asciidoctor'

# Jekyll searches for this groupname ":jekyll_plugins" in your Gemfile
# and requires those gems automatically, (without having to require them
# in the _config.yml file ?!).
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
  gem 'jekyll-seo-tag'
end


# # Useful gems that are not required to build the site
# gem 'jekyll-seo'
# gem 'nokogiri'
